### ISSUE TITLE
Zwift sensor stops updating

### ISSUE THREAD

**Issue by randomstring** [snicker/zwift_hass#13]
On the latest 110.2 of Home assistant and latest HACS and Zwift. I'm seeing the following errors in the logs. The main symptom is that after someone is using Zwift, the status gets stuck as True and the zwift sensor stops updating.

```
  - platform: zwift
    username: !secret zwift_username
    password: !secret zwift_password
    players:
      - !secret zwift_user1_id
      - !secret zwift_user2_id
```

let me know hat other debugging information I can provide. 

```
2020-05-25 21:05:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/zwift/sensor.py", line 117, in update_data
    await hass.async_add_executor_job(zwift_data.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/zwift/sensor.py", line 341, in update
    player_state = world.player_status(player_id)
  File "/usr/local/lib/python3.7/site-packages/zwift/world.py", line 25, in player_status
    '/relay/worlds/{}/players/{}'.format(self.world_id, player_id))
  File "/usr/local/lib/python3.7/site-packages/zwift/request.py", line 45, in protobuf
    resp.status_code, resp.reason))
zwift.error.RequestException: 404 - Not Found
```

**Comment by randomstring** [comment]
Rebooting clears the issue and resets the state of the zwift sensor.

**Comment by randomstring** [comment]
I'm guessing that this is a problem with generating the list of player_id and world_id about line 

```
   File "/config/custom_components/zwift/sensor.py", line 341, in update
     player_state = world.player_status(player_id)
```

If the player state was bad, then the URL generated by `zwift/request.py` will malformed and generate a 404. (the error we're seeing)

The most recent change to this logic was with this pull request:

https://github.com/snicker/zwift_hass/commit/6eb22e59c7c58bdcdb5aeedc8b13c8bbd37602b8

Regardless, this error should have a more graceful recovery mode and not completely wedge the addon and stop all updates. Maybe default the sensor to "False" instead of just getting stuck in the "is riding zwift" state.

**Comment by snicker** [comment]
xposting from HA forums:

what is actually happening is a slight server side mismatch of data due to the frequency at which the data is updated on the server for different endpoints (this is my hypothesis anyway, and what I'll try to verify later)

line 322 will always give us player information about a player, offline or offline:
`_profile = self._client.get_profile(player_id)`
This *will* throw a `401` if the authentication has expired. in which case, we should log back in.
This also tells us whether or not that player is currently `riding`. 

We check this on line 337, and then work on getting more detailed information about the current ride on line 338:
```
if player_profile.get('riding'):
    player_state = world.player_status(player_id)
```

This is where the problem starts: the call on line 338 will return a `404` if the player is not actually riding. So why could this possibly happen? 

My theory: I think these two API calls are out of sync ever so slightly. maybe only 15-30 seconds (enough for an interval to pass and possibly resolve the delta, explaining why this is intermittent). So one call says we're riding, the other says we're not.

I realize now also exactly why this is happening... previously I was capturing all exceptions, then I changed the code to only capture `Exception`... but I was erroneously assuming that the `zwift-client` library was sticking with the Pythonic approach of "user defined exceptions should inherit from `Exception`"... but I was wrong! and foolish... `zwift.error.RequestException` actually inherits from BaseException and is *not* being caught.... sigh
